const crypto = require('crypto');

const palette=['#4285f4','#ea5f91','#8c62d7','#2aa876','#e69b31'];
const stableId=(accountId,remoteId)=>`${accountId}:${crypto.createHash('sha1').update(String(remoteId)).digest('hex').slice(0,12)}`;
async function jsonRequest(url,accessToken,options={}){const response=await fetch(url,{...options,headers:{authorization:`Bearer ${accessToken}`,'content-type':'application/json',...(options.headers||{})}});const data=response.status===204?null:await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message||data?.error_description||`Remote server returned ${response.status}.`);return data;}

function googleEvent(item,calendarId){const allDay=Boolean(item.start?.date);const start=allDay?new Date(`${item.start.date}T00:00:00`):new Date(item.start?.dateTime);const end=allDay?new Date(`${item.end.date}T00:00:00`):new Date(item.end?.dateTime);return{id:`google:${calendarId}:${item.id}`,calendarId,title:item.summary||'(No title)',start:start.toISOString(),end:end.toISOString(),location:item.location||undefined,notes:item.description||undefined,allDay,syncState:'synced',remoteId:item.id,updatedAt:item.updated||new Date().toISOString()};}
async function pagedGoogle(url,accessToken){const items=[];let pageToken;do{const page=await jsonRequest(url+(url.includes('?')?'&':'?')+(pageToken?`pageToken=${encodeURIComponent(pageToken)}`:''),accessToken);items.push(...(page.items||[]));pageToken=page.nextPageToken;}while(pageToken);return items;}
async function googleSync(account,accessToken){const remoteCalendars=await pagedGoogle('https://www.googleapis.com/calendar/v3/users/me/calendarList?maxResults=250',accessToken);const min=new Date();min.setFullYear(min.getFullYear()-1);const max=new Date();max.setFullYear(max.getFullYear()+2);const calendars=[];for(const [index,remote] of remoteCalendars.entries()){const id=stableId(account.id,remote.id);const query=new URLSearchParams({singleEvents:'true',showDeleted:'false',maxResults:'2500',timeMin:min.toISOString(),timeMax:max.toISOString()});const items=await pagedGoogle(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(remote.id)}/events?${query}`,accessToken);calendars.push({id,remoteId:remote.id,name:remote.summaryOverride||remote.summary||`Google Calendar ${index+1}`,color:remote.backgroundColor||palette[index%palette.length],writable:['owner','writer'].includes(remote.accessRole),events:items.filter(item=>item.status!=='cancelled'&&item.start&&item.end).map(item=>googleEvent(item,id))});}return{calendars};}
function googleBody(event){return{summary:event.title,start:event.allDay?{date:event.start.slice(0,10)}:{dateTime:event.start},end:event.allDay?{date:event.end.slice(0,10)}:{dateTime:event.end},location:event.location||undefined,description:event.notes||undefined};}
async function googlePush(remoteCalendarId,event,accessToken){const base=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(remoteCalendarId)}/events`;const remote=event.remoteId?await jsonRequest(`${base}/${encodeURIComponent(event.remoteId)}`,accessToken,{method:'PATCH',body:JSON.stringify(googleBody(event))}):await jsonRequest(base,accessToken,{method:'POST',body:JSON.stringify(googleBody(event))});return googleEvent(remote,event.calendarId);}

const n=(tag,text,namespace)=>text===undefined?{tag,...(namespace?{namespace}:{})}:{tag,text:String(text),...(namespace?{namespace}:{})};
const branch=(tag,children,namespace)=>({tag,children,...(namespace?{namespace}:{})});
const kids=node=>node?.children||[];const one=(node,tag)=>kids(node).find(child=>child.tag===tag);const many=(node,tag)=>kids(node).filter(child=>child.tag===tag);const value=(node,tag)=>one(node,tag)?.text||'';
const easDate=value=>{if(!value)return null;const match=String(value).match(/(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z?/);return match?new Date(Date.UTC(+match[1],+match[2]-1,+match[3],+match[4],+match[5],+match[6])):new Date(value)};
const easStamp=value=>new Date(value).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
const calendarCodePage={0x05:'Timezone',0x06:'AllDayEvent',0x07:'Attendees',0x08:'Attendee',0x09:'Email',0x0a:'Name',0x0b:'Body',0x0c:'BodyTruncated',0x0d:'BusyStatus',0x0e:'Categories',0x0f:'Category',0x11:'DtStamp',0x12:'EndTime',0x13:'Exception',0x14:'Exceptions',0x15:'Deleted',0x16:'ExceptionStartTime',0x17:'Location',0x18:'MeetingStatus',0x19:'OrganizerEmail',0x1a:'OrganizerName',0x1b:'Recurrence',0x1c:'Type',0x1d:'Until',0x1e:'Occurrences',0x1f:'Interval',0x20:'DayOfWeek',0x21:'DayOfMonth',0x22:'WeekOfMonth',0x23:'MonthOfYear',0x24:'Reminder',0x25:'Sensitivity',0x26:'Subject',0x27:'StartTime',0x28:'UID',0x29:'AttendeeStatus',0x2a:'AttendeeType',0x2b:'DisallowNewTimeProposal',0x2c:'ResponseRequested',0x2d:'AppointmentReplyTime',0x2e:'ResponseType',0x2f:'CalendarType',0x30:'IsLeapMonth',0x31:'FirstDayOfWeek'};
async function wbxmlCodec(){const library=await import('@mvrx/wbxml');const codePage={};for(const [page,tags] of Object.entries(library.EAS_CODE_PAGES)){codePage[page]={};for(const [name,token] of Object.entries(tags))codePage[page][token]=name;}codePage[4]=calendarCodePage;return{encode:tree=>library.encode(tree,{codePage}),decode:bytes=>library.decode(bytes,{codePage})};}
async function easPost(account,accessToken,command,tree,policyKey='0'){const {encode,decode}=await wbxmlCodec();const endpoint=account.serverUrl||'https://outlook.office365.com/Microsoft-Server-ActiveSync';const params=new URLSearchParams({Cmd:command,User:account.email,DeviceId:crypto.createHash('sha1').update(`unison:${account.id}`).digest('hex').slice(0,32).toUpperCase(),DeviceType:'UnisonCalendar'});const response=await fetch(`${endpoint}?${params}`,{method:'POST',headers:{authorization:`Bearer ${accessToken}`,'content-type':'application/vnd.ms-sync.wbxml','MS-ASProtocolVersion':'14.1','X-MS-PolicyKey':String(policyKey||'0'),'user-agent':'UnisonCalendar/0.1'},body:Buffer.from(encode(tree))});const bytes=new Uint8Array(await response.arrayBuffer());return{status:response.status,tree:bytes.length?decode(bytes):null};}
async function easProvision(account,accessToken,state){const policyType={tag:'PolicyType',page:14,text:'MS-EAS-Provisioning-WBXML'},policy={tag:'Policy',page:14,children:[policyType]},request={tag:'Provision',page:14,children:[{tag:'Policies',page:14,children:[policy]}]};const first=await easPost(account,accessToken,'Provision',request,'0');if(first.status<200||first.status>=300)throw new Error(`Exchange provisioning returned ${first.status}.`);const firstPolicy=one(one(first.tree,'Policies'),'Policy'),temporaryKey=value(firstPolicy,'PolicyKey');if(!temporaryKey)throw new Error('Exchange did not return a provisioning policy key.');const acknowledge={tag:'Provision',page:14,children:[{tag:'Policies',page:14,children:[{tag:'Policy',page:14,children:[{tag:'PolicyType',page:14,text:'MS-EAS-Provisioning-WBXML'},{tag:'PolicyKey',page:14,text:temporaryKey},{tag:'Status',page:14,text:'1'}]}]}]};const second=await easPost(account,accessToken,'Provision',acknowledge,temporaryKey);if(second.status<200||second.status>=300)throw new Error(`Exchange policy acknowledgement returned ${second.status}.`);state.policyKey=value(one(one(second.tree,'Policies'),'Policy'),'PolicyKey')||temporaryKey;}
async function easRequest(account,accessToken,command,tree,state={}){let response=await easPost(account,accessToken,command,tree,state.policyKey||'0');if(response.status===449){await easProvision(account,accessToken,state);response=await easPost(account,accessToken,command,tree,state.policyKey);}if(response.status<200||response.status>=300)throw new Error(`Exchange ActiveSync returned ${response.status}.`);return response.tree;}
async function easFolders(account,accessToken,state){const tree={tag:'FolderSync',page:7,children:[{tag:'SyncKey',page:7,text:state.folderSyncKey||'0'}]};const response=await easRequest(account,accessToken,'FolderSync',tree,state);const status=value(response,'Status');if(status&&status!=='1')throw new Error(`Exchange FolderSync failed with status ${status}.`);const key=value(response,'SyncKey')||state.folderSyncKey||'0';const changes=one(response,'Changes');const previous=new Map((state.folders||[]).map(folder=>[folder.remoteId,folder]));for(const add of [...many(changes,'Add'),...many(changes,'Update')]){const type=Number(value(add,'Type'));const remoteId=value(add,'ServerId');if((type===8||type===13)&&remoteId)previous.set(remoteId,{remoteId,name:value(add,'DisplayName')||'Exchange Calendar'});}for(const del of many(changes,'Delete'))previous.delete(value(del,'ServerId'));return{folders:[...previous.values()],folderSyncKey:key};}
function easEvent(appData,calendarId,serverId){const start=easDate(value(appData,'StartTime')),end=easDate(value(appData,'EndTime'));if(!start||!end)return null;return{id:`eas:${calendarId}:${serverId}`,calendarId,title:value(appData,'Subject')||'(No title)',start:start.toISOString(),end:end.toISOString(),location:value(appData,'Location')||undefined,allDay:value(appData,'AllDayEvent')==='1',syncState:'synced',remoteId:serverId,updatedAt:new Date().toISOString()};}
async function easCalendar(account,accessToken,folder,syncKey='0',state={}){const id=stableId(account.id,folder.remoteId);let key=syncKey;const events=new Map();let more=true;while(more){const wasInitial=key==='0';const collection=branch('Collection',[n('SyncKey',key,'AirSync'),n('CollectionId',folder.remoteId,'AirSync'),n('DeletesAsMoves','0','AirSync'),n('GetChanges','1','AirSync'),n('WindowSize','512','AirSync'),branch('Options',[n('FilterType','0','AirSync')],'AirSync')],'AirSync');const response=await easRequest(account,accessToken,'Sync',branch('Sync',[branch('Collections',[collection],'AirSync')],'AirSync'),state);const result=one(one(response,'Collections'),'Collection');const status=value(result,'Status');if(status&&status!=='1')throw new Error(`Exchange calendar sync failed with status ${status}.`);const nextKey=value(result,'SyncKey')||key;if(wasInitial&&nextKey==='0')throw new Error('Exchange did not issue an initial calendar sync key.');key=nextKey;const commands=one(result,'Commands');for(const change of [...many(commands,'Add'),...many(commands,'Change')]){const serverId=value(change,'ServerId'),event=easEvent(one(change,'ApplicationData'),id,serverId);if(event)events.set(serverId,event);}for(const del of many(commands,'Delete'))events.delete(value(del,'ServerId'));more=wasInitial||Boolean(one(result,'MoreAvailable'));}return{calendar:{id,remoteId:folder.remoteId,name:folder.name,color:'#1673d1',writable:true,events:[...events.values()]},syncKey:key};}
async function easSync(account,accessToken,state={}){const mutableState={...state};const hierarchy=await easFolders(account,accessToken,mutableState);const calendars=[],syncKeys={};for(const folder of hierarchy.folders){const synced=await easCalendar(account,accessToken,folder,'0',mutableState);calendars.push(synced.calendar);syncKeys[folder.remoteId]=synced.syncKey;}return{calendars,state:{...mutableState,folderSyncKey:hierarchy.folderSyncKey,folders:hierarchy.folders,syncKeys}};}
function easAppData(event){return branch('ApplicationData',[n('Subject',event.title,'Calendar'),n('StartTime',easStamp(event.start),'Calendar'),n('EndTime',easStamp(event.end),'Calendar'),n('AllDayEvent',event.allDay?'1':'0','Calendar'),n('BusyStatus','2','Calendar'),...(event.location?[n('Location',event.location,'Calendar')]:[]) ],'AirSync');}
async function easPush(account,remoteCalendarId,event,accessToken,syncKey,state={}){const command=event.remoteId?branch('Change',[n('ServerId',event.remoteId,'AirSync'),easAppData(event)],'AirSync'):branch('Add',[n('ClientId',crypto.randomUUID(),'AirSync'),easAppData(event)],'AirSync');const collection=branch('Collection',[n('SyncKey',syncKey,'AirSync'),n('CollectionId',remoteCalendarId,'AirSync'),n('DeletesAsMoves','0','AirSync'),n('GetChanges','0','AirSync'),branch('Commands',[command],'AirSync')],'AirSync');const response=await easRequest(account,accessToken,'Sync',branch('Sync',[branch('Collections',[collection],'AirSync')],'AirSync'),state);const result=one(one(response,'Collections'),'Collection'),status=value(result,'Status');if(status&&status!=='1')throw new Error(`Exchange update failed with status ${status}.`);const newKey=value(result,'SyncKey')||syncKey;const addResponse=one(one(result,'Responses'),'Add');const serverId=event.remoteId||value(addResponse,'ServerId');return{event:{...event,id:`eas:${event.calendarId}:${serverId}`,remoteId:serverId,syncState:'synced',updatedAt:new Date().toISOString()},syncKey:newKey,state};}

module.exports={googleSync,googlePush,easSync,easPush};
