import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Cloud, CloudOff, Menu, Plus, RotateCw, Search, Settings, X } from 'lucide-react';
import type { CalendarEvent, CalendarSource, ViewMode } from './types';
import { database } from './db';
import type { ConnectedAccount } from './electron';
import { parseIcs } from './ics';
import { makeSeedEvents, seedCalendars } from './seed';
import { addDays, dateKey, monthGridStart, monthTitle, sameDay, shortDay, startOfDay, startOfWeek, time } from './dateUtils';

const HOURS=Array.from({length:24},(_,i)=>i);

export function App(){
  const [view,setView]=useState<ViewMode>('week'); const [selected,setSelected]=useState(startOfDay(new Date()));
  const [calendars,setCalendars]=useState<CalendarSource[]>([]); const [events,setEvents]=useState<CalendarEvent[]>([]);
  const [online,setOnline]=useState(navigator.onLine); const [ready,setReady]=useState(false); const [editor,setEditor]=useState<{day:Date;event?:CalendarEvent}|null>(null);
  const [query,setQuery]=useState(''); const [sidebar,setSidebar]=useState(true);
  const [settings,setSettings]=useState(false);
  useEffect(()=>{(async()=>{let cs=await database.calendars();let es=await database.events();if(!cs.length){cs=seedCalendars;await Promise.all(cs.map(database.putCalendar));}if(!es.length){es=makeSeedEvents();await Promise.all(es.map(e=>database.saveEvent(e,'create')));}if(navigator.onLine&&window.unison){const accounts=await window.unison.accounts.list();for(const account of accounts.filter(a=>a.provider==='ics')){const synced=await window.unison.accounts.syncIcs(account.id);if(synced.ok){const items=parseIcs(synced.ics,account.id);await database.replaceCalendarEvents(account.id,items);es=[...es.filter(e=>e.calendarId!==account.id),...items]}}}setCalendars(cs);setEvents(es);setReady(true);})();},[]);
  useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
  const visibleEvents=useMemo(()=>events.filter(e=>calendars.find(c=>c.id===e.calendarId)?.visible&&(query===''||`${e.title} ${e.location||''}`.toLowerCase().includes(query.toLowerCase()))),[events,calendars,query]);
  const navigate=(n:number)=>setSelected(d=>view==='month'?new Date(d.getFullYear(),d.getMonth()+n,1):addDays(d,n*(view==='week'?7:1)));
  const title=view==='day'?new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long'}).format(selected):view==='week'?`${new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short'}).format(startOfWeek(selected))} – ${new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:'numeric'}).format(addDays(startOfWeek(selected),6))}`:monthTitle(selected);
  async function save(d:Partial<CalendarEvent>){const now=new Date().toISOString();const e:CalendarEvent={id:d.id||crypto.randomUUID(),calendarId:d.calendarId||calendars[0].id,title:d.title||'Nieuwe afspraak',start:d.start!,end:d.end!,location:d.location,syncState:'pending',updatedAt:now};await database.saveEvent(e,d.id?'update':'create');setEvents(x=>[...x.filter(v=>v.id!==e.id),e]);setEditor(null);}
  if(!ready)return <div className="loading"><CalendarDays size={34}/><span>Je agenda wordt lokaal geopend…</span></div>;
  return <div className={`app ${sidebar?'':'sidebar-hidden'}`}>
    <header className="topbar"><button className="icon" onClick={()=>setSidebar(!sidebar)}><Menu/></button><div className="brand"><span className="logo"><CalendarDays/></span><span>Unison</span></div><button className="today" onClick={()=>setSelected(startOfDay(new Date()))}>Vandaag</button><div className="nav"><button className="icon" onClick={()=>navigate(-1)}><ChevronLeft/></button><button className="icon" onClick={()=>navigate(1)}><ChevronRight/></button></div><h1>{title}</h1><div className="search"><Search/><input aria-label="Zoeken" placeholder="Zoeken" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div><div className="segmented">{(['day','week','month'] as ViewMode[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{{day:'Dag',week:'Week',month:'Maand'}[v]}</button>)}</div><button className="icon" onClick={()=>setSettings(true)} title="Accounts en instellingen"><Settings/></button></header>
    <aside><button className="new-event" onClick={()=>setEditor({day:selected})}><Plus/> Nieuwe afspraak</button><MiniMonth date={selected} onPick={setSelected}/><section><h3>Mijn agenda's</h3>{calendars.map(c=><label className="calendar-row" key={c.id}><input type="checkbox" checked={c.visible} onChange={()=>setCalendars(a=>a.map(x=>x.id===c.id?{...x,visible:!x.visible}:x))}/><span className="dot" style={{background:c.color}}/><span>{c.name}</span><small>{c.provider==='exchange'?'Exchange':c.provider==='google'?'Google':c.provider==='caldav'?'CalDAV':c.provider==='ics'?'ICS-abonnement':'Lokaal'}</small></label>)}</section><div className={`status ${online?'online':'offline'}`}>{online?<Cloud/>:<CloudOff/>}<div><strong>{online?'Gesynchroniseerd':'Offline modus'}</strong><span>{online?'Zojuist bijgewerkt':'Wijzigingen worden bewaard'}</span></div>{online&&<RotateCw/>}</div></aside>
    <main>{view==='month'?<MonthView selected={selected} events={visibleEvents} calendars={calendars} onPick={d=>{setSelected(d);setView('day')}} onCreate={day=>setEditor({day})}/>:<TimeGrid days={view==='day'?[selected]:Array.from({length:7},(_,i)=>addDays(startOfWeek(selected),i))} events={visibleEvents} calendars={calendars} onCreate={day=>setEditor({day})} onEdit={e=>setEditor({day:new Date(e.start),event:e})}/>}</main>
    {editor&&<EventEditor initial={editor} calendars={calendars} onClose={()=>setEditor(null)} onSave={save}/>} 
    {settings&&<AccountSettings onClose={()=>setSettings(false)} onCalendarAdded={(calendar,items)=>{setCalendars(a=>[...a.filter(c=>c.id!==calendar.id),calendar]);setEvents(a=>[...a.filter(e=>e.calendarId!==calendar.id),...items])}}/>} 
  </div>
}

function TimeGrid({days,events,calendars,onCreate,onEdit}:{days:Date[];events:CalendarEvent[];calendars:CalendarSource[];onCreate:(d:Date)=>void;onEdit:(e:CalendarEvent)=>void}){
  const now=new Date();return <div className="time-view"><div className="day-head"><div className="tz">GMT+2</div>{days.map(d=><div key={dateKey(d)} className={sameDay(d,now)?'current':''}><span>{shortDay(d)}</span><b>{d.getDate()}</b></div>)}</div><div className="scroll-grid"><div className="time-labels">{HOURS.map(h=><span key={h}>{h?`${String(h).padStart(2,'0')}:00`:''}</span>)}</div><div className="days-grid" style={{gridTemplateColumns:`repeat(${days.length},1fr)`}}>{days.map(day=><div className="day-column" key={dateKey(day)} onDoubleClick={()=>onCreate(day)}>{HOURS.map(h=><div className="hour" key={h}/>)}{events.filter(e=>sameDay(new Date(e.start),day)).map(e=>{const s=new Date(e.start),end=new Date(e.end),top=(s.getHours()+s.getMinutes()/60)*64,height=Math.max(28,(end.getTime()-s.getTime())/3600000*64),c=calendars.find(x=>x.id===e.calendarId)!;return <button key={e.id} className="event" style={{top,height,background:`${c.color}18`,borderLeftColor:c.color,color:c.color}} onClick={()=>onEdit(e)}><strong>{e.title}</strong><span>{time(e.start)} – {time(e.end)}</span>{e.location&&<small>{e.location}</small>}</button>})}{sameDay(day,now)&&<div className="now-line" style={{top:(now.getHours()+now.getMinutes()/60)*64}}><i/></div>}</div>)}</div></div></div>
}

function MonthView({selected,events,calendars,onPick,onCreate}:{selected:Date;events:CalendarEvent[];calendars:CalendarSource[];onPick:(d:Date)=>void;onCreate:(d:Date)=>void}){const start=monthGridStart(selected);return <div className="month-view"><div className="month-weekdays">{['ma','di','wo','do','vr','za','zo'].map(d=><div key={d}>{d}</div>)}</div><div className="month-grid">{Array.from({length:42},(_,i)=>addDays(start,i)).map(day=><div className={`month-cell ${day.getMonth()!==selected.getMonth()?'muted':''} ${sameDay(day,new Date())?'today-cell':''}`} key={dateKey(day)} onClick={()=>onPick(day)} onDoubleClick={e=>{e.stopPropagation();onCreate(day)}}><b>{day.getDate()}</b>{events.filter(e=>sameDay(new Date(e.start),day)).slice(0,4).map(e=>{const c=calendars.find(x=>x.id===e.calendarId)!;return <div className="month-event" key={e.id}><i style={{background:c.color}}/><span>{time(e.start)}</span><strong>{e.title}</strong></div>})}</div>)}</div></div>}

function MiniMonth({date,onPick}:{date:Date;onPick:(d:Date)=>void}){const start=monthGridStart(date);return <div className="mini"><div className="mini-title"><strong>{monthTitle(date)}</strong><span>‹ &nbsp;›</span></div><div className="mini-grid">{['m','d','w','d','v','z','z'].map((d,i)=><small key={i}>{d}</small>)}{Array.from({length:42},(_,i)=>addDays(start,i)).map(d=><button key={dateKey(d)} className={`${d.getMonth()!==date.getMonth()?'dim':''} ${sameDay(d,date)?'selected':''} ${sameDay(d,new Date())?'today':''}`} onClick={()=>onPick(d)}>{d.getDate()}</button>)}</div></div>}

function EventEditor({initial,calendars,onClose,onSave}:{initial:{day:Date;event?:CalendarEvent};calendars:CalendarSource[];onClose:()=>void;onSave:(d:Partial<CalendarEvent>)=>void}){const e=initial.event;const base=e?new Date(e.start):new Date(initial.day);if(!e)base.setHours(9,0,0,0);const iso=(d:Date)=>{const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};const [title,setTitle]=useState(e?.title||'');const [start,setStart]=useState(iso(base));const [end,setEnd]=useState(iso(e?new Date(e.end):new Date(base.getTime()+3600000)));const [calendarId,setCalendarId]=useState(e?.calendarId||calendars[0].id);const [location,setLocation]=useState(e?.location||'');return <div className="modal-layer" onMouseDown={onClose}><form className="editor" onMouseDown={x=>x.stopPropagation()} onSubmit={x=>{x.preventDefault();onSave({...e,title,start:new Date(start).toISOString(),end:new Date(end).toISOString(),calendarId,location})}}><div className="editor-head"><h2>{e?'Afspraak wijzigen':'Nieuwe afspraak'}</h2><button type="button" onClick={onClose}><X/></button></div><input className="title-input" autoFocus required placeholder="Titel" value={title} onChange={x=>setTitle(x.target.value)}/><label>Begint<input type="datetime-local" value={start} onChange={x=>setStart(x.target.value)}/></label><label>Eindigt<input type="datetime-local" value={end} onChange={x=>setEnd(x.target.value)}/></label><label>Agenda<select value={calendarId} onChange={x=>setCalendarId(x.target.value)}>{calendars.map(c=><option key={c.id} value={c.id}>{c.name} · {c.provider}</option>)}</select></label><label>Locatie<input value={location} onChange={x=>setLocation(x.target.value)} placeholder="Voeg locatie toe"/></label><p className="offline-note">De afspraak wordt direct lokaal opgeslagen en bij de volgende verbinding gesynchroniseerd.</p><div className="editor-actions"><button type="button" onClick={onClose}>Annuleer</button><button className="primary">Bewaar</button></div></form></div>}

function AccountSettings({onClose,onCalendarAdded}:{onClose:()=>void;onCalendarAdded:(calendar:CalendarSource,events:CalendarEvent[])=>void}){
  const [accounts,setAccounts]=useState<ConnectedAccount[]>([]); const [kind,setKind]=useState<'google'|'exchange'|'caldav'|'ics'|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [clientId,setClientId]=useState(''); const [tenant,setTenant]=useState('common'); const [serverUrl,setServerUrl]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState('');
  const [icsName,setIcsName]=useState(''); const [icsUrl,setIcsUrl]=useState('');
  const api=window.unison?.accounts;
  useEffect(()=>{api?.list().then(setAccounts)},[api]);
  async function login(){if(!api)return setError('Accountlogin werkt alleen in de Electron desktopapp.');setBusy(true);setError('');try{const result=kind==='google'?await api.loginGoogle({clientId}):kind==='exchange'?await api.loginMicrosoft({clientId,tenant}):kind==='ics'?await api.subscribeIcs({name:icsName,url:icsUrl}):await api.loginCalDav({serverUrl,username,password});if(result.ok){setAccounts(a=>[...a,result.account]);const icsText='ics' in result&&typeof result.ics==='string'?result.ics:'';if(kind==='ics'&&icsText){const calendar:CalendarSource={id:result.account.id,name:result.account.displayName,color:'#2aa876',provider:'ics',visible:true,account:result.account.id};const items=parseIcs(icsText,result.account.id);await database.putCalendar(calendar);await database.replaceCalendarEvents(calendar.id,items);onCalendarAdded(calendar,items)}setKind(null);setClientId('');setPassword('');setIcsUrl('');setIcsName('')}else setError(result.error)}finally{setBusy(false)}}
  async function remove(id:string){if(!api)return;await api.remove(id);setAccounts(a=>a.filter(x=>x.id!==id))}
  return <div className="modal-layer" onMouseDown={onClose}><div className="settings-panel" onMouseDown={e=>e.stopPropagation()}><div className="editor-head"><div><h2>Accounts</h2><p>Verbind je agenda's. Inloggegevens worden versleuteld op dit apparaat.</p></div><button onClick={onClose}><X/></button></div>
    <div className="account-list">{accounts.length===0&&<div className="empty-account">Nog geen accounts verbonden.</div>}{accounts.map(a=><div className="account-card" key={a.id}><span className={`provider-icon ${a.provider}`}>{a.provider==='google'?'G':a.provider==='exchange'?'M':a.provider==='ics'?'I':'C'}</span><div><strong>{a.displayName}</strong><span>{a.provider==='google'?'Google Calendar':a.provider==='exchange'?'Microsoft Exchange':a.provider==='ics'?'ICS-abonnement':'CalDAV'} · {a.email}</span></div><button onClick={()=>remove(a.id)}>Verwijder</button></div>)}</div>
    {!kind?<><h3>Account of abonnement toevoegen</h3><div className="provider-buttons"><button onClick={()=>setKind('google')}><b className="google">G</b><span>Google Calendar<small>Inloggen met Google</small></span></button><button onClick={()=>setKind('exchange')}><b className="exchange">M</b><span>Microsoft Exchange<small>Microsoft 365 / ActiveSync</small></span></button><button onClick={()=>setKind('caldav')}><b className="caldav">C</b><span>CalDAV<small>iCloud, Fastmail of eigen server</small></span></button><button onClick={()=>setKind('ics')}><b className="ics">I</b><span>Agenda via URL<small>ICS-abonnement, alleen lezen</small></span></button></div></>:<div className="login-form"><button className="back" onClick={()=>{setKind(null);setError('')}}>← Terug</button><h3>{kind==='google'?'Google Calendar':kind==='exchange'?'Microsoft Exchange':kind==='ics'?'ICS-agenda':'CalDAV'} verbinden</h3>{kind==='caldav'?<><label>Serveradres<input autoFocus placeholder="https://calendar.example.com/dav" value={serverUrl} onChange={e=>setServerUrl(e.target.value)}/></label><label>Gebruikersnaam<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Wachtwoord of app-wachtwoord<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p>Voor iCloud gebruik je een app-specifiek wachtwoord.</p></>:kind==='ics'?<><label>Naam<input autoFocus placeholder="Bijvoorbeeld Werkrooster" value={icsName} onChange={e=>setIcsName(e.target.value)}/></label><label>Online agenda-URL<input type="url" placeholder="https://example.com/calendar.ics" value={icsUrl} onChange={e=>setIcsUrl(e.target.value)}/></label><p>De agenda wordt alleen-lezen toegevoegd en lokaal bewaard voor offline gebruik.</p></>:<><label>OAuth client-id<input autoFocus placeholder={kind==='google'?'123…apps.googleusercontent.com':'Applicatie-id uit Microsoft Entra'} value={clientId} onChange={e=>setClientId(e.target.value)}/></label>{kind==='exchange'&&<label>Tenant<input value={tenant} onChange={e=>setTenant(e.target.value)} placeholder="common of tenant-id"/></label>}<p>Na doorgaan opent de beveiligde loginpagina in je standaardbrowser.</p></>}{error&&<div className="login-error">{error}</div>}<button className="connect" disabled={busy} onClick={login}>{busy?'Bezig met verbinden…':'Doorgaan en verbinden'}</button></div>}
  </div></div>
}
