import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Cloud, CloudOff, Menu, Plus, RotateCw, Search, Settings, X } from 'lucide-react';
import type { CalendarEvent, CalendarSource, ViewMode } from './types';
import { database } from './db';
import type { ConnectedAccount, RemoteCalendarPayload } from './electron';
import { calendarColorFromIcs, parseIcs } from './ics';
import { addDays, dateKey, monthGridStart, monthTitle, sameDay, shortDay, startOfDay, startOfWeek, time } from './dateUtils';

const HOURS=Array.from({length:24},(_,i)=>i);
function normalized(value?:string){return (value||'').trim().replace(/\s+/g,' ').toLocaleLowerCase()}
function eventFingerprint(event:CalendarEvent){return [event.calendarId,new Date(event.start).toISOString(),new Date(event.end).toISOString(),event.allDay?'1':'0',normalized(event.title),normalized(event.location)].join('\u001f')}
function deduplicateEvents(items:CalendarEvent[]){const result:CalendarEvent[]=[],indexes=new Map<string,number>();const rank=(event:CalendarEvent)=>event.syncState==='synced'?3:event.syncState==='pending'?2:1;for(const event of items){const keys=[`id:${event.id}`,`content:${eventFingerprint(event)}`];if(event.remoteId)keys.push(`remote:${event.calendarId}\u001f${event.remoteId}\u001f${new Date(event.start).toISOString()}`);const index=keys.map(key=>indexes.get(key)).find(value=>value!==undefined);if(index===undefined){const next=result.length;result.push(event);for(const key of keys)indexes.set(key,next)}else if(rank(event)>rank(result[index])){result[index]=event;for(const key of keys)indexes.set(key,index)}}return result}
function eventsFromRemoteCalendar(calendar:RemoteCalendarPayload){const items=calendar.events?calendar.events:(calendar.resources||calendar.ics.map(ics=>({ics,href:''}))).flatMap(resource=>{try{return parseIcs(resource.ics,calendar.id).map(event=>resource.href?{...event,remoteId:resource.href}:event)}catch(error){console.warn('Remote calendar item could not be parsed',error);return[]}});return deduplicateEvents(items)}
function sourceFromRemote(account:ConnectedAccount,remote:RemoteCalendarPayload,existing?:CalendarSource):CalendarSource{const sourceColor=remote.color||existing?.sourceColor||'#4f7df3';return{id:remote.id,name:remote.name,color:existing?.colorOverride||sourceColor,sourceColor,colorOverride:existing?.colorOverride,provider:account.provider,visible:existing?.visible??true,account:account.id,remoteId:remote.remoteId,writable:remote.writable??account.provider!=='ics'}}
function sourceFromIcs(account:ConnectedAccount,text:string,existing?:CalendarSource):CalendarSource{const sourceColor=calendarColorFromIcs(text)||existing?.sourceColor||'#2aa876';return{id:account.id,name:account.displayName,color:existing?.colorOverride||sourceColor,sourceColor,colorOverride:existing?.colorOverride,provider:'ics',visible:existing?.visible??true,account:account.id,writable:false}}
function allDayCovers(event:CalendarEvent,day:Date){const target=startOfDay(day).getTime(),start=startOfDay(new Date(event.start)).getTime(),end=startOfDay(new Date(event.end)).getTime();return target>=start&&target<Math.max(end,start+86400000)}
function displayEndDate(event:CalendarEvent){const end=new Date(event.end);return event.allDay?addDays(end,-1):end}
function spansDays(event:CalendarEvent){return !sameDay(new Date(event.start),displayEndDate(event))}
function eventCoversDay(event:CalendarEvent,day:Date){if(event.allDay)return allDayCovers(event,day);const target=startOfDay(day).getTime();return target>=startOfDay(new Date(event.start)).getTime()&&target<=startOfDay(new Date(event.end)).getTime()}
function layoutTimedEvents(items:CalendarEvent[]){const sorted=[...items].sort((a,b)=>new Date(a.start).getTime()-new Date(b.start).getTime()||new Date(a.end).getTime()-new Date(b.end).getTime());const result:Array<{event:CalendarEvent;column:number;columns:number}>=[];let group:Array<{event:CalendarEvent;column:number;columns:number}>=[],groupEnd=0,laneEnds:number[]=[];const finish=()=>{const columns=Math.max(1,laneEnds.length);for(const item of group)item.columns=columns;result.push(...group);group=[];laneEnds=[]};for(const event of sorted){const start=new Date(event.start).getTime(),end=new Date(event.end).getTime();if(group.length&&start>=groupEnd)finish();let column=laneEnds.findIndex(laneEnd=>laneEnd<=start);if(column<0)column=laneEnds.length;laneEnds[column]=end;group.push({event,column,columns:1});groupEnd=Math.max(groupEnd,end)}if(group.length)finish();return result}
async function flushPending(calendars:CalendarSource[],events:CalendarEvent[]){if(!window.unison||!navigator.onLine)return events;let current=events;for(const entry of await database.outbox()){const event=current.find(item=>item.id===entry.eventId),calendar=event&&calendars.find(item=>item.id===event.calendarId);if(!event||!calendar||calendar.provider==='local'||calendar.provider==='ics')continue;const pushed=await window.unison.events.push({accountId:calendar.account,provider:calendar.provider,remoteCalendarId:calendar.remoteId,event});if(pushed.ok){await database.replaceEvent(event.id,pushed.event);await database.clearOutboxForEvent(event.id);current=[...current.filter(item=>item.id!==event.id&&item.id!==pushed.event.id),pushed.event]}}return current}

export function App(){
  const [view,setView]=useState<ViewMode>('week'); const [selected,setSelected]=useState(startOfDay(new Date()));
  const [calendars,setCalendars]=useState<CalendarSource[]>([]); const [events,setEvents]=useState<CalendarEvent[]>([]);
  const [online,setOnline]=useState(navigator.onLine); const [ready,setReady]=useState(false); const [editor,setEditor]=useState<{day:Date;event?:CalendarEvent}|null>(null);
  const [details,setDetails]=useState<CalendarEvent|null>(null);
  const [query,setQuery]=useState(''); const [sidebar,setSidebar]=useState(true);
  const [settings,setSettings]=useState(false);
  const [syncing,setSyncing]=useState(false); const [syncError,setSyncError]=useState('');
  useEffect(()=>{(async()=>{let cs=await database.calendars();let es=deduplicateEvents(await database.events());const demoIds=cs.filter(c=>[['work','johan@studio.nl'],['personal','iCloud / CalDAV'],['team','Exchange'],['birthdays','Lokaal']].some(([id,account])=>c.id===id&&c.account===account)).map(c=>c.id);for(const id of demoIds)await database.removeCalendar(id);if(demoIds.length){cs=cs.filter(c=>!demoIds.includes(c.id));es=es.filter(e=>!demoIds.includes(e.calendarId))}es=deduplicateEvents(await flushPending(cs,es));if(navigator.onLine&&window.unison){const accounts=await window.unison.accounts.list(),accountIds=new Set(accounts.map(a=>a.id)),orphanIds=cs.filter(c=>c.provider!=='local'&&!accountIds.has(c.account)).map(c=>c.id);for(const id of orphanIds)await database.removeCalendar(id);if(orphanIds.length){cs=cs.filter(c=>!orphanIds.includes(c.id));es=es.filter(e=>!orphanIds.includes(e.calendarId))}for(const account of accounts){if(account.provider==='ics'){const synced=await window.unison.accounts.syncIcs(account.id);if(synced.ok){const source=sourceFromIcs(account,synced.ics,cs.find(c=>c.id===account.id)),items=deduplicateEvents(parseIcs(synced.ics,account.id));await database.putCalendar(source);await database.replaceCalendarEvents(account.id,items);cs=[...cs.filter(c=>c.id!==source.id),source];es=deduplicateEvents([...es.filter(e=>e.calendarId!==account.id),...items])}}else{const synced=await window.unison.accounts.syncRemote(account.id);if(synced.ok){for(const remote of synced.calendars){const source=sourceFromRemote(account,remote,cs.find(c=>c.id===remote.id)),pending=es.filter(e=>e.calendarId===remote.id&&e.syncState!=='synced'),items=deduplicateEvents([...eventsFromRemoteCalendar(remote),...pending]);await database.putCalendar(source);await database.replaceCalendarEvents(source.id,items);cs=[...cs.filter(c=>c.id!==source.id),source];es=deduplicateEvents([...es.filter(e=>e.calendarId!==source.id),...items])}}}}}es=deduplicateEvents(es);await database.replaceAllEvents(es);setCalendars(cs);setEvents(es);setReady(true);})();},[]);
  useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
  useEffect(()=>{if(ready&&online)flushPending(calendars,events).then(setEvents).catch(console.error)},[online,ready]);
  useEffect(()=>{if(!ready||!window.unison)return;window.unison.accounts.list().then(async accounts=>{const ids=new Set(accounts.map(a=>a.id)),orphans=calendars.filter(c=>c.provider!=='local'&&!ids.has(c.account));if(!orphans.length)return;await Promise.all(orphans.map(c=>database.removeCalendar(c.id)));const orphanIds=new Set(orphans.map(c=>c.id));setCalendars(current=>current.filter(c=>!orphanIds.has(c.id)));setEvents(current=>current.filter(e=>!orphanIds.has(e.calendarId)))})},[ready]);
  const visibleEvents=useMemo(()=>deduplicateEvents(events).filter(e=>calendars.find(c=>c.id===e.calendarId)?.visible&&(query===''||`${e.title} ${e.location||''}`.toLowerCase().includes(query.toLowerCase()))),[events,calendars,query]);
  const navigate=(n:number)=>setSelected(d=>view==='month'?new Date(d.getFullYear(),d.getMonth()+n,1):addDays(d,n*(view==='week'?7:1)));
  const writableCalendars=calendars.filter(c=>c.provider!=='ics'&&c.writable!==false);
  const createEvent=(day:Date)=>writableCalendars.length?setEditor({day}):setSettings(true);
  async function setCalendarColor(calendar:CalendarSource,color:string){const updated={...calendar,color,colorOverride:color};await database.putCalendar(updated);setCalendars(current=>current.map(c=>c.id===calendar.id?updated:c))}
  async function toggleCalendar(calendar:CalendarSource){const updated={...calendar,visible:!calendar.visible};await database.putCalendar(updated);setCalendars(current=>current.map(c=>c.id===calendar.id?updated:c))}
  async function syncNow(){if(!online||!window.unison||syncing)return;setSyncing(true);setSyncError('');try{let cs=await database.calendars(),es=deduplicateEvents(await database.events());es=deduplicateEvents(await flushPending(cs,es));const accounts=await window.unison.accounts.list();for(const account of accounts){if(account.provider==='ics'){const synced=await window.unison.accounts.syncIcs(account.id);if(!synced.ok)throw new Error(`${account.displayName}: ${synced.error}`);const source=sourceFromIcs(account,synced.ics,cs.find(c=>c.id===account.id)),items=deduplicateEvents(parseIcs(synced.ics,account.id));await database.putCalendar(source);await database.replaceCalendarEvents(account.id,items);cs=[...cs.filter(c=>c.id!==source.id),source];es=deduplicateEvents([...es.filter(e=>e.calendarId!==account.id),...items])}else{const synced=await window.unison.accounts.syncRemote(account.id);if(!synced.ok)throw new Error(`${account.displayName}: ${synced.error}`);for(const remote of synced.calendars){const source=sourceFromRemote(account,remote,cs.find(c=>c.id===remote.id)),pending=es.filter(e=>e.calendarId===remote.id&&e.syncState!=='synced'),items=deduplicateEvents([...eventsFromRemoteCalendar(remote),...pending]);await database.putCalendar(source);await database.replaceCalendarEvents(source.id,items);cs=[...cs.filter(c=>c.id!==source.id),source];es=deduplicateEvents([...es.filter(e=>e.calendarId!==source.id),...items])}}}await database.replaceAllEvents(es);setCalendars(cs);setEvents(es)}catch(error){setSyncError(error instanceof Error?error.message:String(error))}finally{setSyncing(false)}}
  async function removeAccountData(accountId:string){const owned=calendars.filter(c=>c.account===accountId);await Promise.all(owned.map(c=>database.removeCalendar(c.id)));setCalendars(current=>current.filter(c=>c.account!==accountId));setEvents(current=>current.filter(e=>!owned.some(c=>c.id===e.calendarId)))}
  const title=view==='day'?new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long'}).format(selected):view==='week'?`${new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short'}).format(startOfWeek(selected))} – ${new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:'numeric'}).format(addDays(startOfWeek(selected),6))}`:monthTitle(selected);
  async function save(d:Partial<CalendarEvent>){const now=new Date().toISOString();let e:CalendarEvent={id:d.id||crypto.randomUUID(),calendarId:d.calendarId||calendars[0].id,title:d.title||'Nieuwe afspraak',start:d.start!,end:d.end!,location:d.location,notes:d.notes,allDay:d.allDay,syncState:'pending',remoteId:d.remoteId,updatedAt:now};const originalId=e.id;await database.saveEvent(e,d.id?'update':'create');setEvents(x=>[...x.filter(v=>v.id!==e.id),e]);setEditor(null);const calendar=calendars.find(c=>c.id===e.calendarId);if(calendar&&calendar.provider!=='local'&&calendar.provider!=='ics'&&navigator.onLine&&window.unison){const pushed=await window.unison.events.push({accountId:calendar.account,provider:calendar.provider,remoteCalendarId:calendar.remoteId,event:e});if(pushed.ok){e=pushed.event;await database.replaceEvent(originalId,e);await database.clearOutboxForEvent(originalId);setEvents(x=>[...x.filter(v=>v.id!==originalId&&v.id!==e.id),e])}else{e={...e,syncState:'error'};await database.putEvent(e);setEvents(x=>[...x.filter(v=>v.id!==e.id),e]);console.error(pushed.error)}}}
  if(!ready)return <div className="loading"><CalendarDays size={34}/><span>Je agenda wordt lokaal geopend…</span></div>;
  return <div className={`app ${sidebar?'':'sidebar-hidden'}`}>
    <header className="topbar"><button className="icon" onClick={()=>setSidebar(!sidebar)}><Menu/></button><div className="brand"><span className="logo"><CalendarDays/></span><span>Unison</span></div><button className="today" onClick={()=>setSelected(startOfDay(new Date()))}>Vandaag</button><div className="nav"><button className="icon" onClick={()=>navigate(-1)}><ChevronLeft/></button><button className="icon" onClick={()=>navigate(1)}><ChevronRight/></button></div><h1>{title}</h1><div className="search"><Search/><input aria-label="Zoeken" placeholder="Zoeken" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div><div className="segmented">{(['day','week','month'] as ViewMode[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{{day:'Dag',week:'Week',month:'Maand'}[v]}</button>)}</div><button className="icon" onClick={()=>setSettings(true)} title="Accounts en instellingen"><Settings/></button></header>
    <aside><button className="new-event" onClick={()=>createEvent(selected)}><Plus/> Nieuwe afspraak</button><MiniMonth date={selected} onPick={setSelected}/><section><h3>Mijn agenda's</h3>{calendars.length===0&&<p className="no-calendars">Nog geen agenda's toegevoegd.</p>}{calendars.map(c=><div className={`calendar-row ${c.visible?'':'calendar-hidden'}`} key={c.id}><label className="color-control" title="Kleur wijzigen"><span className="dot" style={{background:c.color}}/><input type="color" value={c.color} onChange={e=>setCalendarColor(c,e.target.value)}/></label><button className="calendar-name" onClick={()=>toggleCalendar(c)}><span>{c.name}</span><small>{c.provider==='exchange'?'Exchange':c.provider==='google'?'Google':c.provider==='caldav'?'CalDAV':c.provider==='ics'?'ICS-abonnement':'Lokaal'}</small></button></div>)}</section><div className={`status ${online?'online':'offline'} ${syncError?'sync-failed':''}`}>{online?<Cloud/>:<CloudOff/>}<div><strong>{syncing?'Synchroniseren…':syncError?'Synchronisatie mislukt':online?'Gesynchroniseerd':'Offline modus'}</strong><span title={syncError}>{syncError|| (online?'Klik om bij te werken':'Wijzigingen worden bewaard')}</span></div>{online&&<button className="sync-button" onClick={syncNow} disabled={syncing} aria-label="Agenda's synchroniseren" title="Nu synchroniseren"><RotateCw className={syncing?'spinning':''}/></button>}</div></aside>
    <main>{view==='month'?<MonthView selected={selected} events={visibleEvents} calendars={calendars} onPick={d=>{setSelected(d);setView('day')}} onCreate={createEvent} onOpen={setDetails}/>:<TimeGrid days={view==='day'?[selected]:Array.from({length:7},(_,i)=>addDays(startOfWeek(selected),i))} events={visibleEvents} calendars={calendars} onCreate={createEvent} onOpen={setDetails}/>}</main>
    {details&&<EventDetails event={details} calendar={calendars.find(c=>c.id===details.calendarId)} onClose={()=>setDetails(null)} onEdit={()=>{setEditor({day:new Date(details.start),event:details});setDetails(null)}}/>}
    {editor&&<EventEditor initial={editor} calendars={writableCalendars} onClose={()=>setEditor(null)} onSave={save}/>} 
    {settings&&<AccountSettings onClose={()=>setSettings(false)} onAccountRemoved={removeAccountData} onCalendarAdded={(calendar,items)=>{setCalendars(a=>[...a.filter(c=>c.id!==calendar.id),calendar]);setEvents(a=>deduplicateEvents([...a.filter(e=>e.calendarId!==calendar.id),...items]))}}/>} 
  </div>
}

function TimeGrid({days,events,calendars,onCreate,onOpen}:{days:Date[];events:CalendarEvent[];calendars:CalendarSource[];onCreate:(d:Date)=>void;onOpen:(e:CalendarEvent)=>void}){
  const now=new Date(),rangeStart=startOfDay(days[0]),rangeEnd=addDays(startOfDay(days[days.length-1]),1);
  const segments=events.filter(e=>(e.allDay||spansDays(e))&&new Date(e.start)<rangeEnd&&displayEndDate(e)>=rangeStart).map(event=>{const first=Math.max(0,Math.round((startOfDay(new Date(event.start)).getTime()-rangeStart.getTime())/86400000));const last=Math.min(days.length-1,Math.round((startOfDay(displayEndDate(event)).getTime()-rangeStart.getTime())/86400000));return{event,first,last,lane:0,startsBefore:new Date(event.start)<rangeStart,endsAfter:displayEndDate(event)>=rangeEnd}}).sort((a,b)=>a.first-b.first||b.last-a.last);const laneEnds:number[]=[];for(const segment of segments){let lane=laneEnds.findIndex(end=>end<segment.first);if(lane<0)lane=laneEnds.length;segment.lane=lane;laneEnds[lane]=segment.last}const laneCount=Math.max(1,laneEnds.length);
  return <div className="time-view"><div className="day-head"><div className="tz">GMT+2</div>{days.map(d=><div key={dateKey(d)} className={sameDay(d,now)?'current':''}><span>{shortDay(d)}</span><b>{d.getDate()}</b></div>)}</div><div className="all-day-row spanning" style={{gridTemplateColumns:`60px repeat(${days.length},1fr)`,gridTemplateRows:`repeat(${laneCount},26px)`}}><div className="all-day-label" style={{gridRow:`1 / span ${laneCount}`}}>Hele dag</div>{days.map((day,index)=><div className="all-day-cell" style={{gridColumn:index+2,gridRow:`1 / span ${laneCount}`}} key={dateKey(day)} onDoubleClick={()=>onCreate(day)}/>)}{segments.map(segment=>{const c=calendars.find(x=>x.id===segment.event.calendarId)!;return <button key={segment.event.id} className={`all-day-event spanning-event ${segment.startsBefore?'continues-left':''} ${segment.endsAfter?'continues-right':''}`} style={{gridColumn:`${segment.first+2} / ${segment.last+3}`,gridRow:segment.lane+1,background:`${c.color}22`,borderColor:c.color,color:c.color}} onClick={()=>onOpen(segment.event)}>{segment.startsBefore&&<span className="continuation-arrow left">‹</span>}<span className="spanning-title">{segment.event.title}</span>{segment.endsAfter&&<span className="continuation-arrow right">›</span>}</button>})}</div><div className="scroll-grid"><div className="time-labels">{HOURS.map(h=><span key={h}>{h?`${String(h).padStart(2,'0')}:00`:''}</span>)}</div><div className="days-grid" style={{gridTemplateColumns:`repeat(${days.length},1fr)`}}>{days.map(day=><div className="day-column" key={dateKey(day)} onDoubleClick={()=>onCreate(day)}>{HOURS.map(h=><div className="hour" key={h}/>)}{layoutTimedEvents(events.filter(e=>!e.allDay&&!spansDays(e)&&sameDay(new Date(e.start),day))).map(({event:e,column,columns})=>{const s=new Date(e.start),end=new Date(e.end),top=(s.getHours()+s.getMinutes()/60)*64,height=Math.max(28,(end.getTime()-s.getTime())/3600000*64),c=calendars.find(x=>x.id===e.calendarId)!;return <button key={e.id} className="event" style={{top,height,left:`calc(${column*100/columns}% + 4px)`,width:`calc(${100/columns}% - 7px)`,right:'auto',background:`${c.color}18`,borderLeftColor:c.color,color:c.color}} onClick={()=>onOpen(e)}><strong>{e.title}</strong><span>{time(e.start)} – {time(e.end)}</span>{e.location&&<small>{e.location}</small>}</button>})}{sameDay(day,now)&&<div className="now-line" style={{top:(now.getHours()+now.getMinutes()/60)*64}}><i/></div>}</div>)}</div></div></div>
}

function MonthView({selected,events,calendars,onPick,onCreate,onOpen}:{selected:Date;events:CalendarEvent[];calendars:CalendarSource[];onPick:(d:Date)=>void;onCreate:(d:Date)=>void;onOpen:(e:CalendarEvent)=>void}){const start=monthGridStart(selected);return <div className="month-view"><div className="month-weekdays">{['ma','di','wo','do','vr','za','zo'].map(d=><div key={d}>{d}</div>)}</div><div className="month-grid">{Array.from({length:42},(_,i)=>addDays(start,i)).map(day=><div className={`month-cell ${day.getMonth()!==selected.getMonth()?'muted':''} ${sameDay(day,new Date())?'today-cell':''}`} key={dateKey(day)} onClick={()=>onPick(day)} onDoubleClick={e=>{e.stopPropagation();onCreate(day)}}><b>{day.getDate()}</b>{events.filter(e=>(e.allDay||spansDays(e))?eventCoversDay(e,day):sameDay(new Date(e.start),day)).sort((a,b)=>Number(Boolean(b.allDay||spansDays(b)))-Number(Boolean(a.allDay||spansDays(a)))||a.start.localeCompare(b.start)).slice(0,4).map(e=>{const c=calendars.find(x=>x.id===e.calendarId)!,spanning=e.allDay||spansDays(e),startsHere=sameDay(new Date(e.start),day),endsHere=sameDay(displayEndDate(e),day),visualStart=startsHere||day.getDay()===1,visualEnd=endsHere||day.getDay()===0;return spanning?<button className={`month-event month-all-day ${visualStart?'segment-start':'segment-middle'} ${visualEnd?'segment-end':''}`} style={{background:`${c.color}22`,borderLeftColor:c.color,color:c.color}} key={e.id} onClick={click=>{click.stopPropagation();onOpen(e)}}><strong>{visualStart?e.title:'\u00a0'}</strong></button>:<button className="month-event" key={e.id} onClick={click=>{click.stopPropagation();onOpen(e)}}><i style={{background:c.color}}/><span>{time(e.start)}</span><strong>{e.title}</strong></button>})}</div>)}</div></div>}

function MiniMonth({date,onPick}:{date:Date;onPick:(d:Date)=>void}){const start=monthGridStart(date);const move=(amount:number)=>onPick(new Date(date.getFullYear(),date.getMonth()+amount,1));return <div className="mini"><div className="mini-title"><strong>{monthTitle(date)}</strong><div><button aria-label="Vorige maand" onClick={()=>move(-1)}><ChevronLeft/></button><button aria-label="Volgende maand" onClick={()=>move(1)}><ChevronRight/></button></div></div><div className="mini-grid">{['m','d','w','d','v','z','z'].map((d,i)=><small key={i}>{d}</small>)}{Array.from({length:42},(_,i)=>addDays(start,i)).map(d=><button key={dateKey(d)} className={`${d.getMonth()!==date.getMonth()?'dim':''} ${sameDay(d,date)?'selected':''} ${sameDay(d,new Date())?'today':''}`} onClick={()=>onPick(d)}>{d.getDate()}</button>)}</div></div>}

function EventDetails({event,calendar,onClose,onEdit}:{event:CalendarEvent;calendar?:CalendarSource;onClose:()=>void;onEdit:()=>void}){
  const start=new Date(event.start),end=new Date(event.end),shownEnd=displayEndDate(event),dateFormatter=new Intl.DateTimeFormat('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'});const dateText=spansDays(event)?`${dateFormatter.format(start)} – ${dateFormatter.format(shownEnd)}`:dateFormatter.format(start);const status={synced:'Gesynchroniseerd',pending:'Wacht op synchronisatie',error:'Synchronisatie mislukt',conflict:'Synchronisatieconflict'}[event.syncState];const editable=calendar?.provider!=='ics'&&calendar?.writable!==false;
  return <div className="modal-layer" onMouseDown={onClose}><article className="event-details" onMouseDown={e=>e.stopPropagation()}><div className="editor-head"><div className="detail-heading"><i style={{background:calendar?.color||'#4f7df3'}}/><div><h2>{event.title}</h2><span>{calendar?.name||'Onbekende agenda'}</span></div></div><button onClick={onClose} aria-label="Sluiten"><X/></button></div><dl><div><dt>Datum</dt><dd>{dateText}</dd></div><div><dt>Tijd</dt><dd>{event.allDay?'Hele dag':`${time(event.start)} – ${time(event.end)}`}</dd></div>{event.location&&<div><dt>Locatie</dt><dd>{event.location}</dd></div>}{event.notes&&<div><dt>Notities</dt><dd className="detail-notes">{event.notes}</dd></div>}<div><dt>Status</dt><dd><span className={`sync-pill ${event.syncState}`}>{status}</span></dd></div></dl><div className="editor-actions"><button onClick={onClose}>Sluiten</button>{editable&&<button className="primary" onClick={onEdit}>Wijzig afspraak</button>}</div></article></div>
}

function EventEditor({initial,calendars,onClose,onSave}:{initial:{day:Date;event?:CalendarEvent};calendars:CalendarSource[];onClose:()=>void;onSave:(d:Partial<CalendarEvent>)=>void}){const e=initial.event;const base=e?new Date(e.start):new Date(initial.day);if(!e)base.setHours(9,0,0,0);const iso=(d:Date)=>{const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};const [title,setTitle]=useState(e?.title||'');const [start,setStart]=useState(iso(base));const [end,setEnd]=useState(iso(e?new Date(e.end):new Date(base.getTime()+3600000)));const [calendarId,setCalendarId]=useState(e?.calendarId||calendars[0].id);const [location,setLocation]=useState(e?.location||'');return <div className="modal-layer" onMouseDown={onClose}><form className="editor" onMouseDown={x=>x.stopPropagation()} onSubmit={x=>{x.preventDefault();onSave({...e,title,start:new Date(start).toISOString(),end:new Date(end).toISOString(),calendarId,location})}}><div className="editor-head"><h2>{e?'Afspraak wijzigen':'Nieuwe afspraak'}</h2><button type="button" onClick={onClose}><X/></button></div><input className="title-input" autoFocus required placeholder="Titel" value={title} onChange={x=>setTitle(x.target.value)}/><label>Begint<input type="datetime-local" value={start} onChange={x=>setStart(x.target.value)}/></label><label>Eindigt<input type="datetime-local" value={end} onChange={x=>setEnd(x.target.value)}/></label><label>Agenda<select value={calendarId} onChange={x=>setCalendarId(x.target.value)}>{calendars.map(c=><option key={c.id} value={c.id}>{c.name} · {c.provider}</option>)}</select></label><label>Locatie<input value={location} onChange={x=>setLocation(x.target.value)} placeholder="Voeg locatie toe"/></label><p className="offline-note">De afspraak wordt direct lokaal opgeslagen en bij de volgende verbinding gesynchroniseerd.</p><div className="editor-actions"><button type="button" onClick={onClose}>Annuleer</button><button className="primary">Bewaar</button></div></form></div>}

function AccountSettings({onClose,onCalendarAdded,onAccountRemoved}:{onClose:()=>void;onCalendarAdded:(calendar:CalendarSource,events:CalendarEvent[])=>void;onAccountRemoved:(accountId:string)=>Promise<void>}){
  const [accounts,setAccounts]=useState<ConnectedAccount[]>([]); const [kind,setKind]=useState<'google'|'exchange'|'caldav'|'ics'|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [clientId,setClientId]=useState(''); const [tenant,setTenant]=useState('common'); const [serverUrl,setServerUrl]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState('');
  const [icsName,setIcsName]=useState(''); const [icsUrl,setIcsUrl]=useState('');
  const api=window.unison?.accounts;
  useEffect(()=>{api?.list().then(setAccounts)},[api]);
  async function login(){
    if(!api)return setError('Accountlogin werkt alleen in de Electron desktopapp.');setBusy(true);setError('');
    try{
      const result=kind==='google'?await api.loginGoogle({clientId}):kind==='exchange'?await api.loginMicrosoft({clientId,tenant}):kind==='ics'?await api.subscribeIcs({name:icsName,url:icsUrl}):await api.loginCalDav({serverUrl,username,password});
      if(!result.ok){setError(result.error);return}
      setAccounts(a=>[...a,result.account]);const icsText='ics' in result&&typeof result.ics==='string'?result.ics:'';
      if(kind==='ics'&&icsText){const calendar=sourceFromIcs(result.account,icsText),items=deduplicateEvents(parseIcs(icsText,result.account.id));await database.putCalendar(calendar);await database.replaceCalendarEvents(calendar.id,items);onCalendarAdded(calendar,items)}
      let remoteCalendars:RemoteCalendarPayload[]=[];
      if(kind==='caldav'&&'calendars' in result&&Array.isArray(result.calendars))remoteCalendars=result.calendars;
      if((kind==='google'||kind==='exchange')){const synced=await api.syncRemote(result.account.id);if(!synced.ok){setError(`Account connected, but initial synchronization failed: ${synced.error}`);return}remoteCalendars=synced.calendars}
      for(const remote of remoteCalendars){const calendar=sourceFromRemote(result.account,remote),items=eventsFromRemoteCalendar(remote);await database.putCalendar(calendar);await database.replaceCalendarEvents(calendar.id,items);onCalendarAdded(calendar,items)}
      setKind(null);setClientId('');setPassword('');setIcsUrl('');setIcsName('');
    }finally{setBusy(false)}
  }
  async function remove(id:string){if(!api)return;await api.remove(id);await onAccountRemoved(id);setAccounts(a=>a.filter(x=>x.id!==id))}
  return <div className="modal-layer" onMouseDown={onClose}><div className="settings-panel" onMouseDown={e=>e.stopPropagation()}><div className="editor-head"><div><h2>Accounts</h2><p>Verbind je agenda's. Inloggegevens worden versleuteld op dit apparaat.</p></div><button onClick={onClose}><X/></button></div>
    <div className="account-list">{accounts.length===0&&<div className="empty-account">Nog geen accounts verbonden.</div>}{accounts.map(a=><div className="account-card" key={a.id}><span className={`provider-icon ${a.provider}`}>{a.provider==='google'?'G':a.provider==='exchange'?'M':a.provider==='ics'?'I':'C'}</span><div><strong>{a.displayName}</strong><span>{a.provider==='google'?'Google Calendar':a.provider==='exchange'?'Microsoft Exchange':a.provider==='ics'?'ICS-abonnement':'CalDAV'} · {a.email}</span></div><button onClick={()=>remove(a.id)}>Verwijder</button></div>)}</div>
    {!kind?<><h3>Account of abonnement toevoegen</h3><div className="provider-buttons"><button onClick={()=>setKind('google')}><b className="google">G</b><span>Google Calendar<small>Inloggen met Google</small></span></button><button onClick={()=>setKind('exchange')}><b className="exchange">M</b><span>Microsoft Exchange<small>Microsoft 365 / ActiveSync</small></span></button><button onClick={()=>setKind('caldav')}><b className="caldav">C</b><span>CalDAV<small>iCloud, Fastmail of eigen server</small></span></button><button onClick={()=>setKind('ics')}><b className="ics">I</b><span>Agenda via URL<small>ICS-abonnement, alleen lezen</small></span></button></div></>:<div className="login-form"><button className="back" onClick={()=>{setKind(null);setError('')}}>← Terug</button><h3>{kind==='google'?'Google Calendar':kind==='exchange'?'Microsoft Exchange':kind==='ics'?'ICS-agenda':'CalDAV'} verbinden</h3>{kind==='caldav'?<><label>Serveradres<input autoFocus placeholder="https://calendar.example.com/dav" value={serverUrl} onChange={e=>setServerUrl(e.target.value)}/></label><label>Gebruikersnaam<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Wachtwoord of app-wachtwoord<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p>Voor iCloud gebruik je een app-specifiek wachtwoord.</p></>:kind==='ics'?<><label>Naam<input autoFocus placeholder="Bijvoorbeeld Werkrooster" value={icsName} onChange={e=>setIcsName(e.target.value)}/></label><label>Online agenda-URL<input type="url" placeholder="https://example.com/calendar.ics" value={icsUrl} onChange={e=>setIcsUrl(e.target.value)}/></label><p>De agenda wordt alleen-lezen toegevoegd en lokaal bewaard voor offline gebruik.</p></>:<><label>OAuth client-id<input autoFocus placeholder={kind==='google'?'123…apps.googleusercontent.com':'Applicatie-id uit Microsoft Entra'} value={clientId} onChange={e=>setClientId(e.target.value)}/></label>{kind==='exchange'&&<label>Tenant<input value={tenant} onChange={e=>setTenant(e.target.value)} placeholder="common of tenant-id"/></label>}<p>Na doorgaan opent de beveiligde loginpagina in je standaardbrowser.</p></>}{error&&<div className="login-error">{error}</div>}<button className="connect" disabled={busy} onClick={login}>{busy?'Bezig met verbinden…':'Doorgaan en verbinden'}</button></div>}
  </div></div>
}
